config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get "/about" => "pages#about"

  resources :users, only: [:new, :create]
  get "/dashboard" => "users#dashboard"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

  resources :cohorts do
    resources :projects, except: [:index]
    get "/projects" => "projects#cohort_projects_index"
  end

  resources :projects, only: [:index] do
    resources :sites
  end

  resources :tours, only: [:create] do
    get "/sites/:id" => "sites#show_tour", as: "site_with_chat"
    get "/random_site" => "tours#random_site"
  end

  resources :messages, only: [:create, :destroy]
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :cohort
  has_many :members, class_name: "User", through: :cohort
  has_many :sites
  has_many :tours

  def students
    members.where(user_type: 'student')
  end

  def instructors
    members.where(user_type: 'instructor')
  end

  # def self.sort_by_cohort(projects)
  #   projects.reduce({}) do |acc, project|
  #     name = project.cohort.name
  #     if acc[name]
  #       acc[name] << project
  #     else
  #       acc[name] = [project]
  #     end
  #     return acc
  #   end
  #  end

  # def user_site(current_user)
  #   self.sites.find { |site| site.student == current_user }
  # end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # instructor
  def new
    @cohort = Cohort.find(params[:cohort_id])
    @project = Project.new(cohort: @cohort)
  end

  # instructor
  def create
    @cohort = Cohort.find(params[:cohort_id])
    @project = Project.new(project_params)
    @project.cohort = @cohort
    if @project.save
      redirect_to cohort_project_path(@cohort, @project)
    else
      flash[:alert] = "Couldn't create project! Please try again"
      render "new"
    end
  end

  # instructor
  def show
    @project = Project.find(params[:id])
  end

  # student
  def index
    @projects = current_user.projects
    # this feels gnarly as all hell!!!! if i was in javascript world i would simply do a
    # nice reduce and end up with a nifty data structure but that doesn't feel rubyesque!
    # @ pete help
    @project_sites = @projects.map do |project|
      project.sites.find { |sites| sites.student == current_user }
    end
    @user = current_user
  end

  # instructor
  def cohort_projects_index
    @cohort = Cohort.find(params[:cohort_id])
    @projects = @cohort.projects
  end

  private
  def project_params
    params.require(:project).permit(:name, :due_date)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/cohort_projects_index.html.erb
<h1>Projects for <%= @cohort.name %></h1>
<%= link_to("Make a new project", new_cohort_project_path(@cohort)) %>

<% @projects.each do |project| %>
  <h3><%= project.name %></h3>
  <p><%= project.due_date %> (<%= project.sites.count %> submission(s) so far)</p>

  <table>
    <tr>
      <th>Student</th>
      <th>url</th>
    </tr>

    <% project.sites.each do |site| %>
      <tr>
        <td><%= site.student.name %></td>
        <td><%= site.url %></td>
      </tr>
    <% end %>
  </table>
  <p><%= link_to("Start the tour!", tours_path(project_id: project.id), method: "POST") %></p>
<% end %>

app/views/projects/index.html.erb
<div class="projects-container">

  <h3 class="intro">Welcome, <%= @user.name %>!</h3>

  <% if (active_tour = @user.active_tour) %>
    <%= link_to("There's a tour for #{active_tour.name}! Join now!", tour_random_site_path(active_tour), class: "active-tour-button") %>
  <% end %>

  <div class="projects">
    <% @projects.each do |project| %>
      <div class="project">
        <p class="metadata"><%= project.name %> | Cohort <%= project.cohort.name %> | Due <%= project.due_date %></p>
        <!-- here's the corresponding super gnarly piece to the piece in the projects_controller -->
        <% if @project_sites.find { |site| site && project.id == site.project_id } %>
          <p class="project-site"><%= link_to "Your site for this project", project_site_path(project, @project_sites.find { |site| project.id == site.project_id }), class: "project-site-link" %></p>
        <% else %>
          <p class="project-site">You haven't created a site yet for this project. <%= link_to "Create one?", new_project_site_path(project), class: "project-site-link" %>
        <% end %>
        </div>
    <% end %>
  </div>

</div>

app/views/projects/new.html.erb
<%= form_for [@cohort, @project] do |f| %>
  <div>
    <%= f.label :name, class: "for_text_inputs" %>
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div>
    <%= f.label :due_date, class: "for_text_inputs" %>
    <div class="dates"> <%= f.date_select :due_date %></div>
   
  </div>

    <div>
    <%= f.submit :submit %>
  </div>
<% end %>

app/views/projects/show.html.erb
<%= @project.name %>

<p>Submissions so far...</p>

<% @project.sites.each do |site| %>
  <div>
    <%= site.title %>
    <%= site.url %>
  </div>
<% end %>