config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get "/about" => "pages#about"

  resources :users, only: [:new, :create]
  get "/dashboard" => "users#dashboard"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

  resources :cohorts do
    resources :projects, except: [:index]
    get "/projects" => "projects#cohort_projects_index"
  end

  resources :projects, only: [:index] do
    resources :sites
  end

  resources :tours, only: [:create] do
    get "/sites/:id" => "sites#show_tour", as: "site_with_chat"
    get "/random_site" => "tours#random_site"
  end

  resources :messages, only: [:create, :destroy]
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/helpers/_nav.html.erb
<div class="header-container">
  <header>
    <div class="logo"><%= link_to 'science fair', root_path %></div>
    <nav>
      <ul>
        <li class="nav-item"><%= link_to 'About', about_path %></li>
        <% if current_user %>
          <li class="nav-item"><%= link_to 'Dashboard', current_user.is_instructor? ? cohorts_path : projects_path %></li>
          <li class="nav-item"><%= link_to 'Log Out', logout_path, method: :delete %></li>
        <% else %>
          <li class="nav-item"><%= link_to 'Log In', login_path %></li>
          <li class="nav-item"><%= link_to 'Sign Up', new_user_path %></li>
        <% end %>
      </ul>
    </nav>
  </header>
</div>