config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get "/about" => "pages#about"

  resources :users, only: [:new, :create]
  get "/dashboard" => "users#dashboard"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"

  resources :cohorts do
    resources :projects, except: [:index]
    get "/projects" => "projects#cohort_projects_index"
  end

  resources :projects, only: [:index] do
    resources :sites
  end

  resources :tours, only: [:create] do
    get "/sites/:id" => "sites#show_tour", as: "site_with_chat"
    get "/random_site" => "tours#random_site"
  end

  resources :messages, only: [:create, :destroy]
end

app/models/site.rb
class Site < ApplicationRecord
  belongs_to :student, class_name: 'User', foreign_key: :user_id
  belongs_to :project
  has_many :chatrooms
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController

  # student
  def new
    @site = Site.new(project_id: params[:project_id])
    @project = Project.find(params[:project_id])
  end

  # student
  def create
    @site = Site.new(site_params)
    @project = Project.find(params[:project_id])
    @site.project = @project
    @site.student = current_user
    if @site.save!
      redirect_to project_site_path(@project, @site)
    else
      flash[:alert] = "Whoops! Couldn't create the site. Try again!"
      redirect_to new_project_site_path
    end
  end

  # student
  def show
    @site = Site.find(params[:id])
    @project = Project.find(params[:project_id])
  end

  # student
  def edit
    @site = Site.find(params[:id])
    @project = Project.find(params[:project_id])
  end

  # student
  def update
    @site = Site.find(params[:id])
    @project = Project.find(params[:project_id])
    if @site.update(site_params)
      redirect_to project_site_path(@project, @site)
    else
      flash[:alert] = "Could not update site. Try again."
      render "edit"
    end
  end

  # any
  def show_tour
    # this also feels super gnarly, i wonder if it could be, like, better
    @tour = Tour.find(params[:tour_id])
    @site = Site.find(params[:id])
    @visit_helper = VisitSiteHelper.new(visitor: current_user, tour: @tour)
    @current_user_id = current_user.id

    away = CreateMessageHelper.new(tour: @tour, site: @site, user: current_user)
    @message_away = away.new_message
    @away_room = away.messages
    
    if @visit_helper.visitors_own_site
      home = CreateMessageHelper.new(tour: @tour, site: @visit_helper.visitors_own_site, user: current_user)
      @message_home = home.new_message
      @home_room = home.messages
    end
  end

  # instructor
  def index
  end

  def site_params
    params.require(:site).permit(:title, :description, :url, :intro, :github)
  end
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/sites/_bottom_bar.html.erb
<div class="bottom-bar">
  <div class="container">
    <div class="count"><%= visit_helper.sites_already_visited.count %> visited | <%= visit_helper.sites_left_to_visit.count %> remaining</div>
    <div class="next"><%= link_to "Go to next site!", tour_random_site_url(@tour) %></div>
  </div>
</div>

app/views/sites/_display.html.erb
<div class="site-container">
  <div class="title-attr">
    <h3 class="site-title"><%= @site.title %></h3>
    <div class="attr">
      <p class="author">A project by <span><%= @site.student.name %></span></p>
      <p class="links"><a href="<%= @site.url %>" target="_blank">View on the web</a> | <a href="<%= site.github %>" target="_blank">GitHub</a></p>
    </div>
  </div>

  <% if @site.url.include?('youtube') %>
    <% yt_id = @site.url.split('v=')[1] %>
    <iframe width="1400" height="800" src="https://www.youtube.com/embed/<%=yt_id%>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  <% else %>
    <div class="embedded-site">
      <iframe src="<%= @site.url %>" title="<%= @site.title %>" height="900px" width="1400px">Whoops! Site could not be embedded. <a href="<%= @site.url %>">Please visit it here!</a></iframe>
    </div>
  <% end %>

  <div class="description-block">
    <div class="label">Description</div>
    <div class="description"><%= @site.description %></div>
  </div>
</div>

app/views/sites/_form.html.erb
  <%= form_for [project, site] do |f| %>
    <div>
      <%= f.label :title, class: "for_text_inputs" %>
      <%= f.text_field :title, autofocus: true %>
      <p class="description">Keep it short but descriptive! Under 20 characters if you can.</p>
    </div>

    <div>
      <%= f.label :url, class: "for_text_inputs" %>
      <%= f.text_field :url %>
      <p class="description">This is your deployed URL, to Heroku or to a Youtube uploaded screencast.</p>
      <p class="description">If you are using a Youtube link, please make sure your link is in the format <code>https://www.youtube.com/watch?v=YOUR_EMBED_URL</code>.</p>
    </div>

    <div>
      <%= f.label :description, class: "for_text_inputs" %>
      <%= f.text_area :description %>
      <p class="description">Write 3-5 sentences about your project!</p>
    </div>

      <div>
      <%= f.label :github, class: "for_text_inputs" %>
      <%= f.text_field :github %>
      <p class="description">Link to your repository on Github.</p>
    </div>

    <div>
      <%= f.submit :submit %>
    </div>
  <% end %>

app/views/sites/edit.html.erb
<div class="site-form-container">

  <h3>Edit your site!</h3>

  <%= render "form", project: @project, site: @site %>

</div>

app/views/sites/new.html.erb
<div class="site-form-container">

  <h3>Make your site!</h3>

  <%= form_for [@project, @site] do |f| %>
    <div>
      <%= f.label :title, class: "for_text_inputs" %>
      <%= f.text_field :title, autofocus: true %>
      <p class="description">Keep it short but descriptive! Under 20 characters if you can.</p>
    </div>

    <div>
      <%= f.label :url, class: "for_text_inputs" %>
      <%= f.text_field :url %>
      <p class="description">This is your deployed URL, to Heroku or to a Youtube uploaded screencast.</p>
      <p class="description">If you are using a Youtube link, please make sure your link is in the format <code>https://www.youtube.com/watch?v=YOUR_EMBED_URL</code>.</p>
    </div>

    <div>
      <%= f.label :description, class: "for_text_inputs" %>
      <%= f.text_area :description %>
      <p class="description">Write 3-5 sentences about your project!</p>
    </div>

      <div>
      <%= f.label :github, class: "for_text_inputs" %>
      <%= f.text_field :github %>
      <p class="description">Link to your repository on Github.</p>
    </div>

    <div>
      <%= f.submit :submit %>
    </div>
  <% end %>

</div>

app/views/sites/show.html.erb
<%= link_to("Edit this site", edit_project_site_path(@project, @site), class: "edit-button btn--sec")%>

<%= render 'display', site: @site %>

app/views/sites/show_tour.html.erb
<%= render 'display', site: @site %>

<%= render 'bottom_bar', visit_helper: @visit_helper %>

<div class="message-rooms">
  <div class="titles">
    <% if @visit_helper.visitors_own_site %>
      <h3 class="title home"><%= @visit_helper.visitors_own_site.title %></h3>
    <% end %>
    <h3 class="title away active">
      <%= @site.title %>
    </h3>
  </div>
  <div class="message-holders">
    <% if @message_home %>
      <div class="message-room-holder home">
        <div class="message-container">
          <%= render "messages/list", messages: @home_room, current_user_id: @current_user_id %>
        </div>
        <div class="messages-form-container">
          <%= render "messages/form", message: @message_home, class_name: "home", autocomplete: "off" %>
        </div>
      </div>
    <% end %>
    <div class="message-room-holder away">
      <div class="message-container">
          <%= render "messages/list", messages: @away_room, current_user_id: @current_user_id %>
      </div>
      <div class="messages-form-container">
        <%= render "messages/form", message: @message_away, class_name: "away", autocomplete: "off" %>
      </div>
    </div>
  </div>
</div>


<script>
const user_site_id = "<%= @visit_helper.visitors_own_site && @visit_helper.visitors_own_site.id %>"
const current_user_id = "<%= @current_user_id %>"
</script>